### ISSUE TITLE
Enh req: Full sponsorblock & dearrow support

### ISSUE THREAD

**Issue by rodalpho** [fer0n/Unwatched#19]
Excellent app! This could be the iOS equivalent of SmartTube!

My request is simple, full sponsorblock and dearrow support, ideally fully configurable also, to automatically skip sponsored segments and change both thumbnails and titles to be non-clickbait.

**Comment by fer0n** [comment]
Happy to hear you like it :) 

As you probably know, SponsorBlock is already used to enhance chapters and regular ads don't show up (I frankly don't even know why as I've done nothing to actively block them). That is the furthest I'm willing to go regarding interfering with ads and sponsorships. 

Replacing the thumbnails I'd be fine with, but I personally don't see a lot of value in, especially since you only see manually added videos or those from channels you specifically follow.

**Comment by rodalpho** [comment]
Re sponsorblock, sorry to hear that. Of course it is your choice, but I would continue using safari with the sponsorblock extension myself as I find it essential. 

Dearrow is more of a cosmetic thing, many people find clickbait thumbnails and titles annoying, and it uses user-submitted ones to replace.

**Comment by fer0n** [comment]
Just to double check, do you know that you can already enable SponsorBlock chapters? It needs some improvements on iOS 18, but you should be able manually uncheck the chapters you want to skip, including Sponsor segments.

**Comment by rodalpho** [comment]
Yes, I’m aware. Manually skipping is not what I personally want.

**Comment by fer0n** [comment]
Just to clarify again, SponsorBlock is already supported. It simply doesn't do anything automatically, but you can uncheck the sponsor segments ahead of time.

That's currently as far as I'm willing to go. Not that Unwatched is big enough to endanger anyone, but I don't want to actively take something away that YouTube channels rely on to keep making videos. Regular ads don't show up for technical reasons, I'm not doing anything to actively block them either.

**Comment by fer0n** [comment]
I'm assuming creators get all of the money or at least a bigger cut when doing their own sponsorships. When you're paying for premium I think you also shouldn't see any sponsorships, so that's a fair point. Perhaps there's a way to detect if someone has a premium subscription and enable an auto skip in that case.

What I'd be more inclined to add is a more general chapter filter that would let you filter e.g. based on the chapter title and perhaps the chapter type. I don't have any immediate plans for that, though.

**Comment by fer0n** [comment]
I'm considering adding auto skip after confirming a premium subscription which supports creators in a different way – I think that's something I can get behind. 

I don't see a way to actually detect an active premium subscription, so it'll have to be on a trust basis probably.

**Comment by rodalpho** [comment]
That would work for me. I do subscribe to YouTube premium as well as many creators' Patreons. I just don't want to see ads, ever, under any circumstances.
