### ISSUE TITLE
3Blue1Brown shorts show up despite hide shorts on

### ISSUE THREAD

**Issue by MaxPelly** [fer0n/Unwatched#24]
I have hide shorts turned on which seems to get most of them but for some reasons shorts from 3Blue1Brown (https://youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw/videos) seem to make it through to the inbox.
They to show up as \#s instead of the length indicator and the shorts aspect ratio but otherwise look like normal videos.

I'm on test flight version 1.3.3 (156) on the iPadOS 18.2 dev beta.

**Comment by fer0n** [comment]
There's sadly nothing I can do about it. 

The issue is that the video duration, aspect ratio, or - god forbid - even a "short: true/false"  isn't part of the rss feed, so I have to find other ways to detect shorts. Some channels put "#short" in the title or description, which is the easiest detection. When that's not the case, I'm actually loading the thumbnail and checking for black borders on the top/bottom, as shorts usually cover that area with a vertical thumbnail. 

That detection sadly fails when thumbnails have a complete black background, which seems to be the case for most of the videos on that channel.

As soon as the video is loaded up, the aspect ratio and video duration is used to detect it, but at that point it's already too late.

**Comment by fer0n** [comment]
The only other way would be to use the YouTube data api, but that's rate limited and would surely be used up quickly, in which case manually adding videos would no longer work.

You could try your luck and see if that channel is so kind to put "#short" into the video description. Or uses a different background color for their thumbnails.

**Comment by MaxPelly** [comment]
Ah great, gotta love youtube. Ill try hitting them up.
Thanks for all your hard work!

**Comment by fer0n** [comment]
(Thanks for reporting this btw, could very well have been something to fix :)
